#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json
packaging_format = 2

id = "huly"
name = "Huly"
description.en = "Open-Source alternative to Linear and Jira with integrated Chat and Video."
description.fr = "Alternative open-source à Linear et Jira avec Chat et Vidéo intégrés."

version = "0.0.0~ynh1"
maintainers = ["YunoHost-Apps"]

[upstream]
license = "EPL-2.0"
website = "https://huly.io"
code = "https://github.com/hcengineering/huly-selfhost"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "amd64"
multi_instance = true
ldap = false
sso = false
disk = "2000M"
ram.build = "128M"
ram.runtime = "4096M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/hcengineering/huly-selfhost/archive/refs/heads/main.zip"
    sha256 = "be59d868d2fd78e5f6dc563a6821890ab636b99cb65ff0814d1f3f6c098c63ef"
    autoupdate.strategy = "latest_github_release"

    [resources.install_dir]
    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = ["docker.io", "docker-compose-v2"]

    [resources.data_dir]
    
    [resources.ports]
    main.default = 8080
