#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Stopping the service..."
ynh_systemctl --service="$app" --action="stop" --log_path="/var/log/$app/$app.log"

ynh_script_progression "Upgrading source files..."
# Keep our local configs!
ynh_setup_source --dest_dir="$install_dir" --keep=".env compose.yml .huly.nginx data"

ynh_script_progression "Updating configuration..."
ynh_config_add --template=".env" --destination="$install_dir/.env"
ynh_config_add --template="compose.yml" --destination="$install_dir/compose.yml"
ynh_config_add --template=".huly.nginx" --destination="$install_dir/.huly.nginx"

chown -R "$app:www-data" "$install_dir"
chmod -R 750 "$install_dir"

ynh_config_add_nginx
ynh_config_add_systemd
yunohost service add "$app" --description="$app service (Docker)" --log="/var/log/$app/$app.log"

ynh_script_progression "Pulling new Docker images..."
pushd "$install_dir"
    docker-compose --project-name "$app" pull --quiet
popd

ynh_script_progression "Starting the service..."
ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"
sleep 20

ynh_script_progression "Upgrade of $app completed"
